// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./config/models.js";

/**
 * CheckConfig returns true if the main config exists
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckConfig() {
    return $Call.ByID(65391821);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function Connect() {
    return $Call.ByID(164877153);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function Disconnect() {
    return $Call.ByID(3864343059);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVPNLogs() {
    return $Call.ByID(1066339406);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConnected() {
    return $Call.ByID(236330520);
}

/**
 * Lock clears sensitive data from memory and disconnects VPN
 * @returns {$CancellablePromise<void>}
 */
export function Lock() {
    return $Call.ByID(253832250);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup() {
    return $Call.ByID(2232168041);
}

/**
 * SaveConfig encrypts credentials and saves them to the specified path
 * @param {config$0.Credentials} creds
 * @param {string} password
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(creds, password, path) {
    return $Call.ByID(3442292638, creds, password, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectConfigPath() {
    return $Call.ByID(3806290128);
}

/**
 * Unlock attempts to decrypt credentials with the master password
 * @param {string} password
 * @returns {$CancellablePromise<boolean>}
 */
export function Unlock(password) {
    return $Call.ByID(1127700317, password);
}
