// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Credentials {
    /**
     * Creates a new Credentials instance.
     * @param {Partial<Credentials>} [$$source = {}] - The source object to create the Credentials.
     */
    constructor($$source = {}) {
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["server"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["group"] = 0;
        }
        if (!("otp_secret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["otp_secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Credentials instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Credentials}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Credentials(/** @type {Partial<Credentials>} */($$parsedSource));
    }
}
