// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CenterWindow() {
  return window['go']['main']['App']['CenterWindow']();
}

export function CheckConfig() {
  return window['go']['main']['App']['CheckConfig']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVPNLogs() {
  return window['go']['main']['App']['GetVPNLogs']();
}

export function InitSystray(arg1) {
  return window['go']['main']['App']['InitSystray'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function IsConnecting() {
  return window['go']['main']['App']['IsConnecting']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}

export function SelectConfigPath() {
  return window['go']['main']['App']['SelectConfigPath']();
}

export function SyncStatus() {
  return window['go']['main']['App']['SyncStatus']();
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
