// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {config} from '../models';

export function CenterWindow():Promise<void>;

export function CheckConfig():Promise<boolean>;

export function CheckForUpdates():Promise<updater.Release>;

export function Connect():Promise<boolean>;

export function Disconnect():Promise<boolean>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetCredentials():Promise<config.Credentials>;

export function GetVPNLogs():Promise<string>;

export function IsConnected():Promise<boolean>;

export function IsConnecting():Promise<boolean>;

export function Lock():Promise<void>;

export function Log(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Credentials,arg2:string,arg3:string):Promise<void>;

export function SelectConfigPath():Promise<string>;

export function SyncStatus():Promise<boolean>;

export function Unlock(arg1:string):Promise<boolean>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateCredentials(arg1:config.Credentials,arg2:string):Promise<void>;
